### ISSUE TITLE
Backward compatibility 2.8 ↔ 3.0

### ISSUE THREAD

**Issue by ooxi** [phax/jcodemodel#54]
Hi,

I'm considering switching from `com.sun.codemodel` to your implementation since I need a couple of features not present in the original sources.

You are currently doing a refactoring from 2.8 → 3.0 therefore I'm hesitant to switch just yet. Can you inform me about the planned API stability between 2.8 and 3.0 e.g. what will a user of your library have to change when using 2.8 and switching to 3.0?

-- ooxi

**Comment by phax** [comment]
Biggest change is the minimum requirement of JDK 8, but the base API will basically stay. Some Lambdas and some default methods will be added but that's basically it. So switching to 2.8 now and than later to 3.0 should do the trick. Especially because I don't have a schedule for updating to 3.0....

**Comment by ooxi** [comment]
Thanks for the clarification!
